d9 support

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -11,7 +11,7 @@ STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep "
  PHPCS_PATH="$PROJECT/vendor/bin/phpcs"
 # second option:
 # PHPCS_PATH="$PROJECT/bin/phpcs"
-TWIG_LINTER="$PROJECT/vendor/bin/twig-lint"
+#TWIG_LINTER="$PROJECT/vendor/bin/twig-lint"
 
 # Determine if a file list is passed
 if [ "$#" -eq 1 ]
@@ -54,15 +54,15 @@ then
     exit 1
   fi
 
-  echo "Running Twig linter..."
-  for FILE in $FILES
-  do
-    $TWIG_LINTER lint $FILE
-    if [ $? != 0 ]
-    then
-      echo "Fix the error before commit."
-      exit 1
-    fi
+#  echo "Running Twig linter..."
+#  for FILE in $FILES
+#  do
+#    $TWIG_LINTER lint $FILE
+#    if [ $? != 0 ]
+#    then
+#      echo "Fix the error before commit."
+#      exit 1
+#    fi
   done
 
 fi
